### ISSUE TITLE
Problem with pre-trained model of AQUAnet

### ISSUE THREAD

**Issue by PraviMyl** [smhassanerfani/atlantis#12]
I want to test the AQUAnet model in my working area. I had an error in this line: RESTORE_FROM = '../../atlantis_file/snapshots/'+NAME+'/epoch29.pth'
So can you please share your pre-trained model of AQUAnet (trained on your Atlantis dataset)? My email is pravina.m@eng.pdn.ac.lk

**Comment by smhassanerfani** [comment]
Hi Pravina,
give me some time, I'll upload all .pth files on google drive and make it publicly available to download.

thank you
Mohammad

**Comment by PraviMyl** [comment]
Thank you for your concern.

**Comment by smhassanerfani** [comment]
Pravina here is the link for all models trained in this study.
https://drive.google.com/drive/folders/1UqkXVoeCK6bEZ51YmXr1zdFjH5kO9foP?usp=sharing
wish you luck!

**Comment by PraviMyl** [comment]
I'm grateful to you, Mohammad Erfani!

**Comment by PraviMyl** [comment]
When I tested with your AQUAnet model with trained weights, I got the error: 

         RuntimeError: Error(s) in loading state_dict for Aquanet:
	      Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight",.. 
	       size mismatch for context1.2.context.0.weight: copying a param with shape torch.Size([128, 256, 3, 3]) from 
                   checkpoint, the shape in current model is torch.Size([256, 256, 3, 3])"

I think the model you uploaded on your GitHub is unsuitable for the trained weights you uploaded on google drive. If my guess is correct, can you please send me the AQUAnet model that can fit with the trained weights? (epoch29.pth)

**Comment by smhassanerfani** [comment]
The following snippet will help you how to load the model:

`from aquanet import Aquanet
import torch
import torch.nn as nn

model = Aquanet(num_classes=56)
model_dict = model.state_dict()

saved_state_dict = torch.load("epoch29.pth")


for key, value in model_dict.items():
    key_parts_lst = key.split(".")
    if key_parts_lst[0] in ["backbone"]:
        model_dict[key] = saved_state_dict[".".join(key_parts_lst[1:])]
        print(f"bb: {model_dict[key].shape}, {saved_state_dict['.'.join(key_parts_lst[1:])].shape}")
    else:
        model_dict[key] = saved_state_dict[key]
        print(f"rest: {model_dict[key].shape}, {saved_state_dict[key].shape}")`

**Comment by PraviMyl** [comment]
Now the code works well. But I got the wrong results. When I save the outputs, it hasn't any predictions (the predicted image is fully in black color). Can I know the reason for that?
![992914260](https://user-images.githubusercontent.com/111102782/192696214-49c56baa-2748-454e-9805-011c8f1e82b5.png)
![4394931629_color](https://user-images.githubusercontent.com/111102782/192696217-6ea8824c-0eee-4402-85ae-0968ad9d7f5a.png)

**Comment by smhassanerfani** [comment]
Hi
So sorry for late response, let me check to find what the problem is. first thing comes to my mind is wrong trained weights for model. I'll let you know whenever I find the problem.

**Comment by PraviMyl** [comment]
Hi,
Thanks for your support. I tried several times by changing test.py. But I got blank output as before.

**Comment by PraviMyl** [comment]
Hello Mohammad Erfani,

I am really grateful to you and thank you for your support. I hope this
will work

Thanks again

**Comment by gppcaputo** [comment]
i'm trying to perform the test using the weights of DeepLabV3. I follow the snippet that you provided in this issue, but i got the same problems. Can you please help me ? Maybe also the deeplabv3 .pth file is not correct?
