### ISSUE TITLE
How to train my own custom dataset

### ISSUE THREAD

**Issue by JACMoutinho** [smhassanerfani/atlantis#18]
First of all, just want to congratulate you on this work. 

I'm pretty new to deep learning and CNN. I wanted to run my own dataset of images to remove mask water from them. Since i'm pretty new to this, i was wondering if you could give me some pointers on how to do it. 

Thank you so much for your time.
Best regards

**Comment by smhassanerfani** [comment]
Hi,
Thank you! Could you explain what you mean by `to remove mask water from them`?
do you mean that you want to determine the region of water in images and then remove those regions?


Mohammad

**Comment by JACMoutinho** [comment]
Hi. Yes, exactly. Sorry for the botched explanation.

**Comment by smhassanerfani** [comment]
Hello again,
If you want to develop your own dataset, I suggest taking a look at [ATLANTIS DEVELOPMENT KIT](https://github.com/smhassanerfani/atlantis/tree/master/adk). We used [CVAT](https://github.com/opencv/cvat) to annotate our images, it's interactive, free, and versatile, still, there are other options on the web. I assume you know Python programming well, so for the Deep Learning part and to train Deep Learning models to do the task of semantic segmentation, to segment the waterbodies on your images, and to be able to omit those regions from images, you need to have knowledge of Image processing and Deep Learning. I highly recommend this [YouTube](https://www.youtube.com/watch?v=EMXfZB8FVUA&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4) channel for learning PyTorch API, in case you want to pursue this area professionally.

Good Luck
Mohammad

**Comment by JACMoutinho** [comment]
Mohammad, you have been extremely helpful and kind. Thank you so much. I will definitely follow your advice. Also want to congratulate you on your work.

Have a great weekend and all the best.
